# Generated by Django 5.2.10 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatTrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_model', models.CharField(db_index=True, help_text='船型号', max_length=50)),
                ('ship_port', models.IntegerField(blank=True, db_index=True, help_text='来源端口', null=True)),
                ('boat_timestamp', models.CharField(blank=True, help_text='设备时间原始值', max_length=20, null=True)),
                ('device_time', models.DateTimeField(blank=True, db_index=True, help_text='设备时间', null=True)),
                ('status', models.CharField(blank=True, help_text='状态', max_length=50, null=True)),
                ('latitude', models.FloatField(help_text='纬度')),
                ('longitude', models.FloatField(help_text='经度')),
                ('speed', models.FloatField(blank=True, help_text='航速(节)', null=True)),
                ('direction', models.FloatField(blank=True, help_text='航向(度)', null=True)),
                ('battery_voltage', models.FloatField(blank=True, help_text='电压(V)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='入库时间')),
            ],
            options={
                'verbose_name': '船体轨迹记录',
                'verbose_name_plural': '船体轨迹记录',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['ship_model', '-recorded_at'], name='monitoring_b_ship_m_64e7b2_idx'), models.Index(fields=['ship_port', '-recorded_at'], name='monitoring_b_ship_p_c5bac8_idx')],
            },
        ),
    ]
