# Generated by Django 5.2.10 on 2026-03-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_videostreamtransferrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boattrackrecord',
            new_name='monitoring__ship_mo_d4ace8_idx',
            old_name='monitoring_b_ship_m_64e7b2_idx',
        ),
        migrations.RenameIndex(
            model_name='boattrackrecord',
            new_name='monitoring__ship_po_8cd665_idx',
            old_name='monitoring_b_ship_p_c5bac8_idx',
        ),
        migrations.RenameIndex(
            model_name='videostreamtransferrecord',
            new_name='monitoring__ship_mo_1ca8b3_idx',
            old_name='monitoring_v_ship_mo_5f9a04_idx',
        ),
        migrations.RenameIndex(
            model_name='videostreamtransferrecord',
            new_name='monitoring__timesta_f5f3cc_idx',
            old_name='monitoring_v_timesta_7d4fcc_idx',
        ),
    ]
