# Generated by Django 5.2.10 on 2026-02-21 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0, help_text='总任务数')),
                ('completed_tasks', models.IntegerField(default=0, help_text='完成的任务数')),
                ('active_projects', models.IntegerField(default=0, help_text='活跃项目数')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, help_text='总销售额', max_digits=10)),
                ('new_users_count', models.IntegerField(default=0, help_text='新用户数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '仪表板统计',
                'verbose_name_plural': '仪表板统计',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('task_completed', '任务完成'), ('project_created', '项目创建'), ('file_uploaded', '文件上传'), ('other', '其他')], default='other', max_length=50)),
                ('description', models.CharField(help_text='活动描述', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'ordering': ['-created_at'],
            },
        ),
    ]
