# Generated by Django 5.2.10 on 2026-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nutrientdata_waterqualitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(help_text='船型', max_length=50)),
                ('length', models.IntegerField(help_text='长度(cm)')),
                ('model', models.CharField(help_text='型号', max_length=50)),
                ('weight', models.FloatField(help_text='重量(kg)')),
                ('functions', models.CharField(help_text='功能模块', max_length=255)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', help_text='设备状态', max_length=20)),
                ('max_speed', models.FloatField(help_text='最高航速(节)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '无人船设备',
                'verbose_name_plural': '无人船设备',
                'ordering': ['-id'],
            },
        ),
    ]
