# Generated by Django 5.2.10 on 2026-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dronedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='月份 (例如: 1月, 2月)', max_length=10)),
                ('sales', models.IntegerField(help_text='销售金额')),
            ],
            options={
                'verbose_name': '月度销售数据',
                'verbose_name_plural': '月度销售数据',
            },
        ),
        migrations.CreateModel(
            name='UserGrowthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='日期')),
                ('new_users', models.IntegerField(help_text='新增用户数')),
                ('active_users', models.IntegerField(help_text='活跃用户数')),
            ],
            options={
                'verbose_name': '用户增长数据',
                'verbose_name_plural': '用户增长数据',
                'ordering': ['-date'],
            },
        ),
    ]
