# Generated by Django 6.0.1 on 2026-03-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_extend_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutrientData',
        ),
        migrations.DeleteModel(
            name='WaterQualityData',
        ),
    ]
